import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import MenuSidebar from "@/components/sidebar/menu-sidebar";
import AppBar from "@/components/app/app-bar";
import { cn } from "@/lib/utils";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Next.js && Shadcn/ui",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div id="root" className="flex flex-col w-full h-screen">
            <AppBar />
            <div className="flex flex-row w-full h-full">
              <MenuSidebar />
              <div className="flex h-full px-5 py-8">{children}</div>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
